apiVersion: v1
kind: Pod
metadata:
  name: pbj-gvisor-sysbox
  labels:
    app: pbj-gvisor-sysbox
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto:size=65536"
spec:
  runtimeClassName: sysbox-runc
  nodeSelector:
    node-use-type: "sdk-runner"
  tolerations:
    - key: "node-use-type"
      operator: "Equal"
      value: "sdk-runner"
      effect: "NoSchedule"
  containers:
    - name: dind-host
      image: us-docker.pkg.dev/build-286712/non-prod-docker-us/peterj/gvisor:amd-v2
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          memory: 1Gi
  restartPolicy: Never
  terminationGracePeriodSeconds: 5

